package br.edu.fatec.aula;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Scanner;
import javax.swing.JOptionPane;

public class QuizFrame extends javax.swing.JFrame {

    /**
     * Creates new form QuizFrame
     */
    public QuizFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        perguntaTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        resposta1Button = new javax.swing.JButton();
        resposta2Button = new javax.swing.JButton();
        resposta3Button = new javax.swing.JButton();
        resposta4Button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pular1Button = new javax.swing.JButton();
        pular2Button = new javax.swing.JButton();
        pular3Button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numeroAcertosLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        jPanel2.setBackground(new java.awt.Color(52, 152, 219));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        perguntaTextArea.setEditable(false);
        perguntaTextArea.setBackground(new java.awt.Color(52, 152, 219));
        perguntaTextArea.setColumns(20);
        perguntaTextArea.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        perguntaTextArea.setForeground(new java.awt.Color(255, 255, 255));
        perguntaTextArea.setLineWrap(true);
        perguntaTextArea.setRows(5);
        perguntaTextArea.setText("O que um Analista de Sistema faz quando se formar no curso:");
        perguntaTextArea.setWrapStyleWord(true);
        perguntaTextArea.setBorder(null);
        perguntaTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        perguntaTextArea.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane2.setViewportView(perguntaTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));
        jPanel3.setLayout(new java.awt.GridLayout(4, 0, 0, 4));

        resposta1Button.setBackground(new java.awt.Color(149, 165, 166));
        resposta1Button.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        resposta1Button.setForeground(new java.awt.Color(44, 62, 80));
        resposta1Button.setText("Resposta 1");
        resposta1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resposta1ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(resposta1Button);

        resposta2Button.setBackground(new java.awt.Color(149, 165, 166));
        resposta2Button.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        resposta2Button.setForeground(new java.awt.Color(44, 62, 80));
        resposta2Button.setText("Resposta 2");
        resposta2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resposta2ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(resposta2Button);

        resposta3Button.setBackground(new java.awt.Color(149, 165, 166));
        resposta3Button.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        resposta3Button.setForeground(new java.awt.Color(44, 62, 80));
        resposta3Button.setText("Resposta 3");
        resposta3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resposta3ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(resposta3Button);

        resposta4Button.setBackground(new java.awt.Color(149, 165, 166));
        resposta4Button.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        resposta4Button.setForeground(new java.awt.Color(44, 62, 80));
        resposta4Button.setText("Resposta 4");
        resposta4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resposta4ButtonActionPerformed(evt);
            }
        });
        jPanel3.add(resposta4Button);

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));
        jPanel4.setLayout(new java.awt.GridLayout(1, 3, 4, 0));

        pular1Button.setBackground(new java.awt.Color(46, 204, 113));
        pular1Button.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pular1Button.setForeground(new java.awt.Color(44, 62, 80));
        pular1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/imagem/redo-5-24.png"))); // NOI18N
        pular1Button.setText("Pular");
        pular1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pular1ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(pular1Button);

        pular2Button.setBackground(new java.awt.Color(46, 204, 113));
        pular2Button.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pular2Button.setForeground(new java.awt.Color(44, 62, 80));
        pular2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/imagem/redo-5-24.png"))); // NOI18N
        pular2Button.setText("Pular");
        pular2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pular2ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(pular2Button);

        pular3Button.setBackground(new java.awt.Color(46, 204, 113));
        pular3Button.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pular3Button.setForeground(new java.awt.Color(44, 62, 80));
        pular3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/fatec/imagem/redo-5-24.png"))); // NOI18N
        pular3Button.setText("Pular");
        pular3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pular3ButtonActionPerformed(evt);
            }
        });
        jPanel4.add(pular3Button);

        jPanel5.setBackground(new java.awt.Color(44, 62, 80));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219), 2));
        jPanel5.setForeground(new java.awt.Color(52, 152, 219));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ACERTOS");

        numeroAcertosLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        numeroAcertosLabel.setForeground(new java.awt.Color(255, 255, 255));
        numeroAcertosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroAcertosLabel.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 55, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(numeroAcertosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(numeroAcertosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarInformacoesNaTela() {
        String linha = lista.remove(0);
        String[] partes = linha.split("[|]");
        perguntaTextArea.setText(partes[0]);
        resposta1Button.setText(partes[1]);
        resposta2Button.setText(partes[2]);
        resposta3Button.setText(partes[3]);
        resposta4Button.setText(partes[4]);
        numeroRespostaCorreta = Integer.parseInt(partes[5]);
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        String caminho = "src/br/edu/fatec/arquivo/dados.txt";
        File arquivo = new File(caminho);
        try {
            Scanner entrada = new Scanner(arquivo);
            while (entrada.hasNext()) {
                String linha = entrada.nextLine();      // Le uma linha do arquivo
                lista.add(linha);                       // adiciona na Lista  
            }
            Collections.shuffle(lista);                 // Embaralhar a lista

            adicionarInformacoesNaTela();

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,
                    "Falha ao ler o arquivo!",
                    "Erro de Arquivo",
                    JOptionPane.ERROR_MESSAGE);

            dispose();
        }
    }//GEN-LAST:event_formWindowOpened

    private void pular1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pular1ButtonActionPerformed
        pular1Button.setEnabled(false);
        adicionarInformacoesNaTela();
    }//GEN-LAST:event_pular1ButtonActionPerformed

    private void pular2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pular2ButtonActionPerformed
        pular2Button.setEnabled(false);
        adicionarInformacoesNaTela();
    }//GEN-LAST:event_pular2ButtonActionPerformed

    private void pular3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pular3ButtonActionPerformed
        pular3Button.setEnabled(false);
        adicionarInformacoesNaTela();
    }//GEN-LAST:event_pular3ButtonActionPerformed

    private void resposta1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta1ButtonActionPerformed
        if (numeroRespostaCorreta == 1) {
            numeroAcertos++;
            numeroAcertosLabel.setText("" + numeroAcertos);

            adicionarInformacoesNaTela();
        } else {
            JOptionPane.showMessageDialog(null,
                    "Errou. A reposta correta seria a alternativa " + numeroRespostaCorreta,
                    "Gameover",
                    JOptionPane.ERROR_MESSAGE);

            dispose();
        }
    }//GEN-LAST:event_resposta1ButtonActionPerformed

    private void resposta2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta2ButtonActionPerformed
        if (numeroRespostaCorreta == 2) {
            numeroAcertos++;
            numeroAcertosLabel.setText("" + numeroAcertos);

            adicionarInformacoesNaTela();
        } else {
            JOptionPane.showMessageDialog(null,
                    "Errou. A reposta correta seria a alternativa " + numeroRespostaCorreta,
                    "Gameover",
                    JOptionPane.ERROR_MESSAGE);

            dispose();
        }
    }//GEN-LAST:event_resposta2ButtonActionPerformed

    private void resposta3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta3ButtonActionPerformed
        if (numeroRespostaCorreta == 3) {
            numeroAcertos++;
            numeroAcertosLabel.setText("" + numeroAcertos);

            adicionarInformacoesNaTela();
        } else {
            JOptionPane.showMessageDialog(null,
                    "Errou. A reposta correta seria a alternativa " + numeroRespostaCorreta,
                    "Gameover",
                    JOptionPane.ERROR_MESSAGE);

            dispose();
        }
    }//GEN-LAST:event_resposta3ButtonActionPerformed

    private void resposta4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resposta4ButtonActionPerformed
        if (numeroRespostaCorreta == 4) {
            numeroAcertos++;
            numeroAcertosLabel.setText("" + numeroAcertos);

            adicionarInformacoesNaTela();
        } else {
            JOptionPane.showMessageDialog(null,
                    "Errou. A reposta correta seria a alternativa " + numeroRespostaCorreta,
                    "Gameover",
                    JOptionPane.ERROR_MESSAGE);

            dispose();
        }
    }//GEN-LAST:event_resposta4ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizFrame().setVisible(true);
            }
        });
    }

    private int numeroAcertos = 0;
    private int numeroRespostaCorreta;
    private ArrayList<String> lista = new ArrayList<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numeroAcertosLabel;
    private javax.swing.JTextArea perguntaTextArea;
    private javax.swing.JButton pular1Button;
    private javax.swing.JButton pular2Button;
    private javax.swing.JButton pular3Button;
    private javax.swing.JButton resposta1Button;
    private javax.swing.JButton resposta2Button;
    private javax.swing.JButton resposta3Button;
    private javax.swing.JButton resposta4Button;
    // End of variables declaration//GEN-END:variables
}
