/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula;

/**
 *
 * @author Kleber de Oliveira Andrade
 */
public class CalculadoraFrame extends javax.swing.JFrame {

    public CalculadoraFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        umButton = new javax.swing.JButton();
        doisButton = new javax.swing.JButton();
        tresButton = new javax.swing.JButton();
        multButton = new javax.swing.JButton();
        quatroButton = new javax.swing.JButton();
        cincoButton = new javax.swing.JButton();
        seisButton = new javax.swing.JButton();
        subButton = new javax.swing.JButton();
        seteButton = new javax.swing.JButton();
        oitojButton = new javax.swing.JButton();
        noveButton = new javax.swing.JButton();
        somaButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        zeroZeroButton = new javax.swing.JButton();
        pontoButton = new javax.swing.JButton();
        igualButton = new javax.swing.JButton();
        limparButton = new javax.swing.JButton();
        divButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        displayTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aula 1 - Calculadora");
        setBackground(new java.awt.Color(39, 174, 96));
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(52, 73, 94));

        jPanel3.setBackground(new java.awt.Color(44, 62, 80));

        umButton.setBackground(new java.awt.Color(46, 204, 113));
        umButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        umButton.setForeground(new java.awt.Color(44, 62, 80));
        umButton.setText("1");
        umButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umButtonActionPerformed(evt);
            }
        });

        doisButton.setBackground(new java.awt.Color(46, 204, 113));
        doisButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        doisButton.setForeground(new java.awt.Color(44, 62, 80));
        doisButton.setText("2");
        doisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisButtonActionPerformed(evt);
            }
        });

        tresButton.setBackground(new java.awt.Color(46, 204, 113));
        tresButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        tresButton.setForeground(new java.awt.Color(44, 62, 80));
        tresButton.setText("3");
        tresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresButtonActionPerformed(evt);
            }
        });

        multButton.setBackground(new java.awt.Color(26, 188, 156));
        multButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        multButton.setForeground(new java.awt.Color(44, 62, 80));
        multButton.setText("*");
        multButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multButtonActionPerformed(evt);
            }
        });

        quatroButton.setBackground(new java.awt.Color(46, 204, 113));
        quatroButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        quatroButton.setForeground(new java.awt.Color(44, 62, 80));
        quatroButton.setText("4");
        quatroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroButtonActionPerformed(evt);
            }
        });

        cincoButton.setBackground(new java.awt.Color(46, 204, 113));
        cincoButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        cincoButton.setForeground(new java.awt.Color(44, 62, 80));
        cincoButton.setText("5");
        cincoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoButtonActionPerformed(evt);
            }
        });

        seisButton.setBackground(new java.awt.Color(46, 204, 113));
        seisButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        seisButton.setForeground(new java.awt.Color(44, 62, 80));
        seisButton.setText("6");
        seisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisButtonActionPerformed(evt);
            }
        });

        subButton.setBackground(new java.awt.Color(26, 188, 156));
        subButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        subButton.setForeground(new java.awt.Color(44, 62, 80));
        subButton.setText("-");
        subButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subButtonActionPerformed(evt);
            }
        });

        seteButton.setBackground(new java.awt.Color(46, 204, 113));
        seteButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        seteButton.setForeground(new java.awt.Color(44, 62, 80));
        seteButton.setText("7");
        seteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteButtonActionPerformed(evt);
            }
        });

        oitojButton.setBackground(new java.awt.Color(46, 204, 113));
        oitojButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        oitojButton.setForeground(new java.awt.Color(44, 62, 80));
        oitojButton.setText("8");
        oitojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitojButtonActionPerformed(evt);
            }
        });

        noveButton.setBackground(new java.awt.Color(46, 204, 113));
        noveButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        noveButton.setForeground(new java.awt.Color(44, 62, 80));
        noveButton.setText("9");
        noveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveButtonActionPerformed(evt);
            }
        });

        somaButton.setBackground(new java.awt.Color(26, 188, 156));
        somaButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        somaButton.setForeground(new java.awt.Color(44, 62, 80));
        somaButton.setText("+");
        somaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaButtonActionPerformed(evt);
            }
        });

        zeroButton.setBackground(new java.awt.Color(46, 204, 113));
        zeroButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        zeroButton.setForeground(new java.awt.Color(44, 62, 80));
        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        zeroZeroButton.setBackground(new java.awt.Color(46, 204, 113));
        zeroZeroButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        zeroZeroButton.setForeground(new java.awt.Color(44, 62, 80));
        zeroZeroButton.setText("00");
        zeroZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroZeroButtonActionPerformed(evt);
            }
        });

        pontoButton.setBackground(new java.awt.Color(46, 204, 113));
        pontoButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        pontoButton.setForeground(new java.awt.Color(44, 62, 80));
        pontoButton.setText(".");
        pontoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontoButtonActionPerformed(evt);
            }
        });

        igualButton.setBackground(new java.awt.Color(26, 188, 156));
        igualButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        igualButton.setForeground(new java.awt.Color(44, 62, 80));
        igualButton.setText("=");
        igualButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualButtonActionPerformed(evt);
            }
        });

        limparButton.setBackground(new java.awt.Color(26, 188, 156));
        limparButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        limparButton.setForeground(new java.awt.Color(44, 62, 80));
        limparButton.setText("C");
        limparButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparButtonActionPerformed(evt);
            }
        });

        divButton.setBackground(new java.awt.Color(26, 188, 156));
        divButton.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        divButton.setForeground(new java.awt.Color(44, 62, 80));
        divButton.setText("/");
        divButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(limparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(seteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oitojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zeroZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pontoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(igualButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(umButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(doisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(quatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cincoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(somaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limparButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(umButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quatroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cincoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(somaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oitojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(zeroZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pontoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(igualButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));

        displayTextField.setEditable(false);
        displayTextField.setBackground(new java.awt.Color(149, 165, 166));
        displayTextField.setFont(new java.awt.Font("Calculator", 0, 48)); // NOI18N
        displayTextField.setForeground(new java.awt.Color(44, 62, 80));
        displayTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayTextField.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setText("Resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void umButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umButtonActionPerformed
        adicionarValorNoDisplay("1");
    }//GEN-LAST:event_umButtonActionPerformed

    private void doisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisButtonActionPerformed
        adicionarValorNoDisplay("2");
    }//GEN-LAST:event_doisButtonActionPerformed

    private void tresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresButtonActionPerformed
        adicionarValorNoDisplay("3");
    }//GEN-LAST:event_tresButtonActionPerformed

    private void quatroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroButtonActionPerformed
        adicionarValorNoDisplay("4");
    }//GEN-LAST:event_quatroButtonActionPerformed

    private void cincoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoButtonActionPerformed
        adicionarValorNoDisplay("5");
    }//GEN-LAST:event_cincoButtonActionPerformed

    private void seisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisButtonActionPerformed
        adicionarValorNoDisplay("6");
    }//GEN-LAST:event_seisButtonActionPerformed

    private void seteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteButtonActionPerformed
        adicionarValorNoDisplay("7");
    }//GEN-LAST:event_seteButtonActionPerformed

    private void oitojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitojButtonActionPerformed
        adicionarValorNoDisplay("8");
    }//GEN-LAST:event_oitojButtonActionPerformed

    private void noveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveButtonActionPerformed
        adicionarValorNoDisplay("9");
    }//GEN-LAST:event_noveButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        adicionarValorNoDisplay("0");
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void zeroZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroZeroButtonActionPerformed
        adicionarValorNoDisplay("00");
    }//GEN-LAST:event_zeroZeroButtonActionPerformed

    private void pontoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontoButtonActionPerformed
        if (displayTextField.getText().isEmpty()) {
            adicionarValorNoDisplay("0.");
        }

        if (!displayTextField.getText().contains(".")) {
            adicionarValorNoDisplay(".");
        }
    }//GEN-LAST:event_pontoButtonActionPerformed

    private void limparButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparButtonActionPerformed
        displayTextField.setText("");
        operacao = "";
    }//GEN-LAST:event_limparButtonActionPerformed

    private void somaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaButtonActionPerformed
        String display = displayTextField.getText();
        if (display.isEmpty()) {
            return;
        }

        resposta = Double.parseDouble(display);
        displayTextField.setText("");
        operacao = "+";
    }//GEN-LAST:event_somaButtonActionPerformed

    private void subButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subButtonActionPerformed
        String display = displayTextField.getText();
        if (display.isEmpty()) {
            return;
        }

        resposta = Double.parseDouble(display);
        displayTextField.setText("");
        operacao = "-";
    }//GEN-LAST:event_subButtonActionPerformed

    private void multButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multButtonActionPerformed
        String display = displayTextField.getText();
        if (display.isEmpty()) {
            return;
        }

        resposta = Double.parseDouble(display);
        displayTextField.setText("");
        operacao = "*";
    }//GEN-LAST:event_multButtonActionPerformed

    private void divButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divButtonActionPerformed
        String display = displayTextField.getText();
        if (display.isEmpty()) {
            return;
        }

        resposta = Double.parseDouble(display);
        displayTextField.setText("");
        operacao = "/";
    }//GEN-LAST:event_divButtonActionPerformed

    private void igualButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualButtonActionPerformed

        String display = displayTextField.getText();
        if (display.isEmpty()) {
            display = "0";
        }

        Double valor = Double.parseDouble(display);
        switch (operacao) {
            case "+":
                resposta += valor;
                break;

            case "-":
                resposta -= valor;
                break;

            case "*":
                resposta *= valor;
                break;

            case "/":
                resposta /= valor;
                break;
        }
        
        displayTextField.setText(String.valueOf(resposta));
    }//GEN-LAST:event_igualButtonActionPerformed

    private void adicionarValorNoDisplay(String valor) {
        String display = displayTextField.getText();
        display += valor;
        displayTextField.setText(display);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraFrame().setVisible(true);
            }
        });
    }

    private double resposta = 0.0;
    private String operacao = "";

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cincoButton;
    private javax.swing.JTextField displayTextField;
    private javax.swing.JButton divButton;
    private javax.swing.JButton doisButton;
    private javax.swing.JButton igualButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton limparButton;
    private javax.swing.JButton multButton;
    private javax.swing.JButton noveButton;
    private javax.swing.JButton oitojButton;
    private javax.swing.JButton pontoButton;
    private javax.swing.JButton quatroButton;
    private javax.swing.JButton seisButton;
    private javax.swing.JButton seteButton;
    private javax.swing.JButton somaButton;
    private javax.swing.JButton subButton;
    private javax.swing.JButton tresButton;
    private javax.swing.JButton umButton;
    private javax.swing.JButton zeroButton;
    private javax.swing.JButton zeroZeroButton;
    // End of variables declaration//GEN-END:variables
}
