/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.fatec.aula;

/**
 *
 * @author ad0201
 */
public class CalculadoraJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraJFrame
     */
    public CalculadoraJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resultadoTextField = new javax.swing.JTextField();
        numeroUmButton = new javax.swing.JButton();
        operacaoSomarButton = new javax.swing.JButton();
        operacaoIgualarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aula 1 - Calculadora");
        setBackground(new java.awt.Color(204, 0, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(31, 5, 41));

        resultadoTextField.setEditable(false);
        resultadoTextField.setFont(new java.awt.Font("Quartz MS", 0, 24)); // NOI18N
        resultadoTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        resultadoTextField.setToolTipText("Resultado");
        resultadoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoTextFieldActionPerformed(evt);
            }
        });

        numeroUmButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        numeroUmButton.setText("1");
        numeroUmButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        numeroUmButton.setMaximumSize(new java.awt.Dimension(64, 64));
        numeroUmButton.setMinimumSize(new java.awt.Dimension(64, 64));
        numeroUmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroUmButtonActionPerformed(evt);
            }
        });

        operacaoSomarButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        operacaoSomarButton.setText("+");
        operacaoSomarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        operacaoSomarButton.setMaximumSize(new java.awt.Dimension(64, 64));
        operacaoSomarButton.setMinimumSize(new java.awt.Dimension(64, 64));
        operacaoSomarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacaoSomarButtonActionPerformed(evt);
            }
        });

        operacaoIgualarButton.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        operacaoIgualarButton.setText("=");
        operacaoIgualarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        operacaoIgualarButton.setMaximumSize(new java.awt.Dimension(64, 64));
        operacaoIgualarButton.setMinimumSize(new java.awt.Dimension(64, 64));
        operacaoIgualarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacaoIgualarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultadoTextField)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(numeroUmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(operacaoSomarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(operacaoIgualarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultadoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroUmButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(operacaoSomarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(operacaoIgualarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numeroUmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroUmButtonActionPerformed
        String total = resultadoTextField.getText();
        resultadoTextField.setText(total + "1");
    }//GEN-LAST:event_numeroUmButtonActionPerformed

    private void resultadoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultadoTextFieldActionPerformed

    private void operacaoSomarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operacaoSomarButtonActionPerformed

        textoA = resultadoTextField.getText();
        resultadoTextField.setText("");
        operacao = "+";

    }//GEN-LAST:event_operacaoSomarButtonActionPerformed

    private void operacaoIgualarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operacaoIgualarButtonActionPerformed

        textoB = resultadoTextField.getText();
        resultadoTextField.setText("");
        int a = Integer.parseInt(textoA);
        int b = Integer.parseInt(textoB);
        int total = 0;

        switch (operacao) {
            case "+":
                total = a + b;
                break;
        }

        String numero = String.valueOf(total);
        resultadoTextField.setText(numero);

    }//GEN-LAST:event_operacaoIgualarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraJFrame().setVisible(true);
            }
        });
    }

    private String textoA;
    private String textoB;
    private String operacao;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton numeroUmButton;
    private javax.swing.JButton operacaoIgualarButton;
    private javax.swing.JButton operacaoSomarButton;
    private javax.swing.JTextField resultadoTextField;
    // End of variables declaration//GEN-END:variables
}
